### ISSUE TITLE
Create Utility functions for tasks involving more than 3-4 steps

### ISSUE THREAD

**Issue by SujalChoudhari** [SujalChoudhari/SolarisUI#4]
Create a utility function which helps to create high end components with ease.
Create the functions under `Solaris` class. `createPage` is an example

**Comment by harsh-2O** [comment]
@SujalChoudhari can you please assign this issue to me

**Comment by SujalChoudhari** [comment]
@harsh-2O 
What all utility function are you planning to add?
Please provide a list of those.

**Comment by SujalChoudhari** [comment]
Commit c6e4ae2:
With this commit, we have a `createComponent` method that effectively eliminates the need of using Atoms and Atomizer. Hence This task is partially solved.
